'use client'

import { useState } from 'react'
import { BarChart3, Box, ChevronRight, FileText, LayoutDashboard, Menu, Package, Search, Settings, X } from 'lucide-react'

type Screen = 'quotations' | 'projects' | 'inventory' | 'reports'
const quotes = [
  ['Downstream Division Townhall','Energy group','Conference','RM 96,000','Won','4 Sep 2026'],
  ['Enterprise Product Launch','Telco client (enterprise div.)','Product launch','RM 285,000','Won','12 Sep 2026'],
  ['Islamic Banking Annual Dinner','Domestic bank','Gala dinner','RM 420,000','Quoted','27 Sep 2026'],
  ['EV Roadshow (5 cities)','Automotive brand','Roadshow','RM 540,000','KIV','1 Aug 2026'],
  ['Sales Gallery Opening','Property developer','Corporate launch','RM 210,000','Quoted','4 Oct 2026'],
  ['National Breakfast Day activation','FMCG beverage brand','Activation','RM 480,000','Enquiry','8 Nov 2026'],
  ['Private Wedding — Ballroom','Private client','Wedding','RM 88,000','Lost','11 Oct 2026'],
]
const equipment = [['LED walls','6m × 4m','Available'],['Line-array PA','24 boxes','Booked'],['Lighting rig','120 moving heads','In use'],['Staging & truss','48 decks','Available'],['Projectors','12 units','Booked'],['Comms / intercom','8 sets','Available']]
const projects = [['Downstream Division Townhall','Energy group','RM 96,000','RM 78,500','18.2%','In Production'],['Enterprise Product Launch','Telco client','RM 285,000','RM 214,000','24.9%','In Production'],['Islamic Banking Annual Dinner','Domestic bank','RM 420,000','RM 310,000','26.2%','Confirmed'],['Star Awards Night','Shared-services firm','RM 178,000','RM 152,000','14.6%','Delivered'],['Family Day 2026','Insurance group','RM 132,000','RM 118,500','7.7%','Reconciled']]
function Pill({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={`pill ${tone}`}>{children}</span>}
function Shell({screen,setScreen,children}:{screen:Screen;setScreen:(s:Screen)=>void;children:React.ReactNode}){const nav:[Screen,string,typeof LayoutDashboard][]=[['reports','Dashboard',LayoutDashboard],['quotations','Quotations',FileText],['projects','Projects',Box],['inventory','Inventory',Package]];return <div className="myttem"><header className="topbar"><button className="brand" onClick={()=>setScreen('reports')}>Jalakx <small>Powered by Myttem</small></button><div className="global-search"><Search size={16}/><input placeholder="Search anything…"/></div><span className="top-spacer"/><span className="site">Assigned Site(s): None</span><button className="icon-button"><Settings size={17}/></button></header><aside className="rail"><div className="rail-mark">J</div><nav>{nav.map(([key,label,Icon])=><button className={screen===key?'rail-link active':'rail-link'} onClick={()=>setScreen(key)} key={key}><Icon size={18}/><span>{label}</span></button>)}</nav><button className="rail-link"><Menu size={18}/><span>More</span></button></aside><main className="content">{children}</main></div>}
function Header({eyebrow,title,sub,action}:{eyebrow:string;title:string;sub:string;action?:React.ReactNode}){return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function QuoteDetail({onClose}:{onClose:()=>void}){return <div className="drawer-backdrop" onMouseDown={onClose}><aside className="drawer" onMouseDown={e=>e.stopPropagation()}><button className="drawer-close" onClick={onClose}><X size={18}/></button><div className="eyebrow">Won quotation · MYT-Q-0264</div><h2>Downstream Division Townhall</h2><p className="muted">Energy group · Conference · 4 Sep 2026</p><Pill tone="green">chop-and-sign: client signed</Pill><section className="drawer-section"><h3>Proposal structure</h3><div className="proposal-grid"><b>Company & event details</b><span>Event brief, venue, schedule and client contacts</span><b>Image gallery</b><span className="gallery">Event concept imagery</span><b>Costing & budget</b><span>RM 96,000 client-stated ceiling · commercial terms locked</span><b>FAQ</b><span>Production, payment and cancellation notes</span></div></section><section className="drawer-section"><h3>Commercial summary</h3><div className="summary-line"><span>Quoted value</span><strong>RM 96,000</strong></div><div className="summary-line"><span>Gross margin target</span><strong>26%</strong></div></section></aside></div>}
function Quotations(){const [detail,setDetail]=useState(false);return <><Header eyebrow="Sales & CRM" title="Quotations" sub="Build, track, and convert event proposals from first enquiry to signed work." action={<button className="primary">+ New quotation</button>}/><div className="metrics"><Metric label="Open pipeline" value="RM 1.7m" sub="6 active quotations"/><Metric label="Win rate" value="62%" sub="last 12 months"/><Metric label="Awaiting signature" value="2" sub="chop-and-sign"/></div><section className="panel"><div className="panel-head"><div><h2>Quotation pipeline</h2><p>Commercial opportunities across Jalakx.</p></div><div className="filters"><button className="filter active">All stages</button><button className="filter">This quarter</button></div></div><div className="quote-table"><div className="table-head"><span>Opportunity</span><span>Client / type</span><span>Value</span><span>Stage</span><span>Event date</span><span/></div>{quotes.map((q,i)=><button className="table-row" key={q[0]} onClick={()=>q[0].startsWith('Downstream')&&setDetail(true)}><span><b>{q[0]}</b><small>MYT-Q-{String(264-i).padStart(4,'0')}</small></span><span>{q[1]}<small>{q[2]}</small></span><strong>{q[3]}</strong><span><Pill tone={q[4]==='Won'?'green':q[4]==='Lost'?'red':q[4]==='KIV'?'amber':'blue'}>{q[4]}</Pill>{q[4]==='KIV'&&<small className="pro">Auto follow-up: Pro</small>}</span><span>{q[5]}</span><ChevronRight size={16}/></button>)}</div></section>{detail&&<QuoteDetail onClose={()=>setDetail(false)}/>}</>}
function Metric({label,value,sub}:{label:string;value:string;sub:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Projects(){return <><Header eyebrow="Operations" title="Projects" sub="Won quotations become live event projects with budget, margin, and delivery control."/><section className="panel"><div className="panel-head"><div><h2>Active and recent projects</h2><p>Project margin is calculated from committed and actual cost.</p></div><button className="secondary">Export</button></div><div className="data-table"><div className="table-head"><span>Project</span><span>Client</span><span>Quoted</span><span>Actual cost</span><span>Margin</span><span>Status</span></div>{projects.map((p,i)=><div className="table-row" key={p[0]}><span><b>{p[0]}</b><small>{i===0?'Attention · deposit not received':''}</small></span><span>{p[1]}</span><strong>{p[2]}</strong><span>{p[3]}</span><span className={i===0?'warning':'positive'}>{p[4]}</span><Pill tone={i===0?'amber':'blue'}>{p[5]}</Pill></div>)}</div></section><div className="detail-columns"><section className="panel"><h2>Downstream Division Townhall</h2><p className="muted">Energy group · Conference · MITEC Hall 5 · 4 days to go</p><div className="attention"><b>Attention</b><span>Deposit not received — event in 4 days</span><span>2 riggers unconfirmed</span></div><div className="margin-hero"><span>Live gross margin</span><strong>18.2%</strong><small>vs. 26% target</small></div><h3>Budget vs actual</h3><div className="mini-table"><div><span>Venue & F&B</span><b>RM 20,000</b><b>RM 18,500</b></div><div><span>AV / staging / lighting</span><b>RM 31,500</b><b>RM 28,200</b></div><div><span>Crew & technical labour</span><b>RM 13,440</b><b>RM 12,800</b></div><div><span>Transport / logistics</span><b>RM 7,680</b><b>RM 8,200</b></div></div></section><section className="panel"><h2>Delivery Order</h2><p className="muted">DO-0264 · items absorbed into one delivery document.</p><div className="do-item"><span>LED wall and playback</span><Pill tone="green">Ready</Pill></div><div className="do-item"><span>Backdrop — <b>VO</b></span><button className="pro-button">Sign off: Pro</button></div><div className="do-item"><span>Extended crew day — <b>VO</b></span><Pill tone="amber">Pending</Pill></div></section></div></>}
function Inventory(){return <><Header eyebrow="Assets" title="Inventory" sub="Know what is available, booked, and returned across the equipment fleet."/><div className="metrics"><Metric label="Equipment utilisation" value="71%" sub="next 8 weeks"/><Metric label="GRN compliance" value="4 / 5" sub="recent events logged"/><Metric label="Open damage claims" value="RM 4,500" sub="Star Awards Night"/></div><section className="panel"><div className="panel-head"><div><h2>Equipment availability</h2><p>JSL Asia rental fleet · 12–19 Aug 2026</p></div><button className="secondary">Log GRN</button></div><div className="equipment-grid">{equipment.map((e,i)=><div className="equipment-card" key={e[0]}><div className="equipment-icon"><Package size={20}/></div><b>{e[0]}</b><span>{e[1]}</span><Pill tone={e[2]==='Available'?'green':e[2]==='Booked'?'blue':'amber'}>{e[2]}</Pill></div>)}</div></section><section className="panel grn"><div><div className="eyebrow">Delivered event · RM 178,000</div><h2>Star Awards Night</h2><p className="muted">Connexion Bangsar South · 16 Aug 2026 · Shared-services firm</p></div><div className="grn-alert"><strong>GRN not logged</strong><span>Damage claim open: 2 moving lights · RM 4,500. Return was never formally recorded.</span></div><div className="condition-list"><div><span>LED wall 6m × 4m</span><Pill tone="green">Good condition</Pill></div><div><span>Moving lights × 2</span><Pill tone="red">Claim open</Pill></div><div><span>Wireless intercom set</span><Pill tone="green">Good condition</Pill></div></div><div className="pro-section"><b>Condition history: Pro</b><span>Returned in good condition — 12 Aug</span><span>Minor wear noted — 3 Jul</span><span>Serviced and cleared — 18 Jun</span></div></section></>}
function Reports(){return <><Header eyebrow="Management reporting" title="Dashboard" sub="Native Myttem reporting for the decisions Jalakx needs to make every week."/><div className="metrics reports-metrics"><Metric label="Project margin · this quarter" value="19.8%" sub="vs. 26% target"/><Metric label="Quoting pipeline / win rate" value="RM 1.7m · 62%" sub="last 12 months"/><Metric label="Cash position & AR ageing" value="RM 143k overdue" sub="via AutoCount"/><Metric label="Equipment utilisation" value="71%" sub="2 clashes next 8 weeks"/><Metric label="GRN compliance" value="4 / 5" sub="Star Awards Night flagged"/><Metric label="Pipeline analytics · Pro" value="+12.4%" sub="conversion trend"/></div><section className="panel"><div className="panel-head"><div><h2>Won projects</h2><p>Margin and delivery health across live and completed work.</p></div><Pill tone="amber">3 decisions needed</Pill></div><div className="data-table"><div className="table-head"><span>Project</span><span>Status</span><span>Quoted</span><span>Actual cost</span><span>Margin</span><span>Health</span></div>{projects.map((p,i)=><div className="table-row" key={p[0]}><span><b>{p[0]}</b><small>{p[1]}</small></span><Pill tone={i===0?'amber':'blue'}>{p[5]}</Pill><strong>{p[2]}</strong><span>{p[3]}</span><span className={i===0||i===3?'warning':'positive'}>{p[4]}</span><span className={`health ${i===0||i===3?'red':'green'}`}/></div>)}</div></section></>}
export default function Page(){const [screen,setScreen]=useState<Screen>('quotations');return <Shell screen={screen} setScreen={setScreen}>{screen==='quotations'?<Quotations/>:screen==='projects'?<Projects/>:screen==='inventory'?<Inventory/>:<Reports/>}</Shell>}
