'use client'

import { useMemo, useState } from 'react'
import { AlertTriangle, BarChart3, Bell, Box, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, ClipboardList, DollarSign, FileText, Grid2X2, HelpCircle, Home, Menu, Package, Search, Settings, UserCircle, Users, X } from 'lucide-react'

type Event = { id:string; name:string; client:string; date:string; stage:string; status:string; revenue:string; margin:string; risk?:string }
const events:Event[] = [
 {id:'EV-1042',name:'Apex Partner Summit',client:'Apex Group',date:'18 Sep 2026',stage:'Live',status:'On track',revenue:'£184,500',margin:'32%',risk:'Crew gap'},
 {id:'EV-1041',name:'Lumen Product Launch',client:'Lumen',date:'22 Sep 2026',stage:'Build',status:'At risk',revenue:'£96,200',margin:'24%',risk:'Late PO'},
 {id:'EV-1038',name:'Harbour House Awards',client:'Harbour House',date:'03 Oct 2026',stage:'Planning',status:'On track',revenue:'£72,800',margin:'38%'},
 {id:'EV-1036',name:'Northstar Roadshow',client:'Northstar',date:'09 Oct 2026',stage:'Planning',status:'Watch',revenue:'£148,000',margin:'27%',risk:'Budget drift'},
 {id:'EV-1034',name:'Studio Sessions — Series 4',client:'Studio Sessions',date:'14 Oct 2026',stage:'Quote',status:'On track',revenue:'£42,600',margin:'41%'}]
const sales = [['SCI-SO-00004780','Approved','MARS TAN','2026-08-27','BEE EYE ENGINEERING SDN BHD','4550.0000'],['SCI-SO-00004779','In Progress','SHERLLY','2026-08-27','WENG CHEONG HARDWARE TRADING','995.0000'],['SCI-SO-00004778','In Progress','SHERLLY','2026-08-27','ALAF KHAIR TRADING','13275.0000'],['SCI-SO-00004776','Approved','KENNY SAN','2026-08-27','TSR BINA SDN BHD','101149.0000'],['SCI-SO-00004775','In Progress','SHERLLY','2026-08-26','AFHAM SEPERKAT ENTERPRISE','810.0000']]
const inventory = [['CANCEL-ST','CANCEL-ST','Service','Speed Concrete Industries','0','0.00'],['RENTAL - M/SQUARE OFFICE','RENTAL - M/SQUARE OFFICE','Service','Speed Concrete Industries','0','0.00'],['RENTAL - CANTEEN RASA','RENTAL - CANTEEN RASA','Service','Speed Concrete Industries','0','0.00'],['TEST SERVICE 1','SERV01','Service','Speed Concrete Industries','0','0.00'],['TESTFORRENTAL','RENTAL01','Service','Speed Concrete Industries','0','0.00'],['TRANSPORT','SERVICE TRANSPORT','Service','Speed Concrete Industries','0','-']]
const nav = [{label:'Dashboard',icon:Home,key:'dashboard'},{label:'Locations',icon:MapPinIcon,key:'locations'},{label:'Parent Items',icon:Box,key:'parent'},{label:'Items',icon:Package,key:'items'},{label:'Global Search',icon:Search,key:'search'},{label:'Inventory / Assets',icon:Grid2X2,key:'inventory'},{label:'Sales',icon:DollarSign,key:'sales'},{label:'Manufacture',icon:Settings,key:'manufacture'},{label:'Equipment & Crew',icon:Users,key:'equipment'},{label:'Procurement',icon:ClipboardList,key:'procurement'}]
function MapPinIcon({size=18}:{size?:number}){return <span style={{fontSize:size}}>◆</span>}
function Badge({children,tone='blue'}:{children:React.ReactNode;tone?:string}){return <span className={'badge '+tone}>{children}</span>}
function Hero({title,sub}:{title:string;sub:string}){return <div className="hero"><h1>{title}</h1><p>{sub}</p></div>}
function Modal({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>{title}</h2><p>Operational workspace</p></div><button className="close" onClick={onClose} aria-label="Close"><X size={20}/></button></div>{children}</div></div>}
function DataTable({kind}:{kind:'sales'|'inventory'|'procurement'}){const [q,setQ]=useState(''); const rows=kind==='sales'?sales:inventory; const filtered=rows.filter(r=>r.join(' ').toLowerCase().includes(q.toLowerCase())); const headers=kind==='sales'?['Reference','Status','Salesperson','Date','Customer','Grand Total']:['Item','SKU','Type','Company','Total Inventory','Total Inventory Cost']; return <div className="table-card"><div className="table-toolbar"><div className="search"><Search size={16}/><input placeholder={kind==='sales'?'Search sales orders':'Search SKU or Name'} value={q} onChange={e=>setQ(e.target.value)}/></div><button className="blue-button">Search</button><select><option>10</option><option>25</option><option>50</option></select></div><div className="scroll-table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{filtered.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{j===1&&kind==='sales'?<Badge tone={x==='Approved'?'green':'amber'}>{x}</Badge>:x}</td>)}</tr>)}</tbody></table></div><div className="table-foot">Showing 1 to {filtered.length} of {kind==='sales'?'2672':'20'} entries <span><button>‹</button><button className="active-page">1</button><button>2</button><button>3</button><button>›</button></span></div></div>}
function Equipment(){const cells=['booked','clash','full','free','free','booked','free','free','full','clash','booked','booked','full','full','full','booked','free','full','booked','free','booked','free','booked','booked','full','free','booked','free','full','booked','free','booked','free','free','booked','full','free','booked','booked','free','full','free','booked','free','booked','full','free','booked','free']; return <><Hero title="Equipment & Crew" sub="Resource readiness across every event — booked, available, and where the gaps are."/><div className="metrics four"><Metric label="Equipment utilisation" value="71%" sub="weighted across 6 categories"/><Metric label="Clashes — next 8 weeks" value="2" sub="LED walls · line-array PA"/><Metric label="Cross-hire spend — 6 mo" value="RM 180k" sub="trend rising"/><Metric label="Crew gaps — next 2 weeks" value="2" sub="riggers for Townhall (5 Sep)"/></div><section className="panel"><h2>Equipment booking — next 8 weeks</h2><p className="muted">JSL Asia inventory. Where it is committed, free, or double-booked.</p><div className="booking"><div className="booking-row header"><b>Category</b>{['W1','W2','W3','W4','W5','W6','W7','W8'].map(x=><span key={x}>{x}</span>)}</div>{['LED walls','Line-array PA','Lighting rig','Staging & truss','Projectors','Comms / intercom'].map((r,ri)=><div className="booking-row" key={r}><b>{r}</b>{Array.from({length:8},(_,i)=><span className={cells[(ri*8+i)%cells.length]} key={i}>{cells[(ri*8+i)%cells.length]==='clash'?'!!':cells[(ri*8+i)%cells.length]==='full'?'full':''}</span>)}</div>)}</div><div className="legend"><span><i className="free"/>Free</span><span><i className="booked"/>Booked, headroom</span><span><i className="full"/>Fully committed</span><span><i className="clash"/>Over-committed (clash)</span></div></section><div className="two-col"><section className="panel"><h2>Sub-rental spend — last 6 months</h2><p className="muted">Gear rented from other suppliers because it was booked out or not owned.</p><div className="sparkline"><i/><i/><i/><i/><i/><i/></div><p>≈ RM 360k a year at the current run rate.</p></section><section className="panel"><h2>Freelance crew — next 2 weeks</h2>{[['Rigger — A. Faizal','Head rigger','locked'],['Rigger — S. Kumar','Rigger','GAP'],['Rigger — J. Anand','Rigger','GAP'],['LX — Mei Ling','Lighting op','locked'],['A1 — Roland P.','Sound engineer','on hold']].map(x=><div className="crew-row" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><Badge tone={x[2]==='GAP'?'red':x[2]==='on hold'?'amber':'green'}>{x[2]}</Badge></div>)}</section></div></>}
function Metric({label,value,sub}:{label:string;value:string;sub:string}){return <div className="metric"><div className="eyebrow">{label}</div><strong>{value}</strong><span>{sub}</span></div>}
function Dashboard({setPopup}:{setPopup:(x:string)=>void}){return <><Hero title="Dashboard" sub="Overview"/><main className="dashboard"><h2>My Daily Overviews</h2><div className="metrics six">{[['Created','0'],['Draft','0'],['In Progress','0'],['Staging','0'],['Completed','0'],['Cancelled','0']].map(x=><Metric key={x[0]} label={x[0]} value={x[1]} sub="Today"/>)}</div><section className="panel"><div className="panel-title"><h2>Task Distribution</h2><button className="refresh">↻</button></div><div className="empty-charts"><div>◔<br/><span>No data available</span></div><div>◔<br/><span>No data available</span></div></div></section><section className="panel task-groups">{['Equipment & Crew','Sales','Purchasing','Logistics'].map((x,i)=><button key={x} onClick={()=>i===0?setPopup('equipment'):i===1?setPopup('sales'):setPopup('procurement')}><b>{x}</b><ChevronDown size={16}/>{i===0&&<span className="task-pills">Adjust 0　 Transfer 0　 Repackage 0　 Inbound 0　 Outbound 0</span>}</button>)}</section></main></>}
export default function Page(){const [popup,setPopup]=useState(''); const [mobile,setMobile]=useState(false); const [view,setView]=useState('dashboard'); const [dark,setDark]=useState(true); const title=nav.find(n=>n.key===view)?.label||'Dashboard'; return <div className={dark?'app dark':'app'}><header className="topbar"><button className="menu" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><b>MYTTEM</b><div className="top-search"><input/><button><Search size={17}/></button><button><Grid2X2 size={17}/></button></div><div className="top-right"><button onClick={()=>setDark(!dark)}>{dark?'☼':'◐'}</button><span>Assigned Site(s): None</span><UserCircle size={17}/></div></header><aside className={mobile?'sidebar open':'sidebar'}><div className="side-head"><b>MYTTEM</b><button onClick={()=>setMobile(false)}><Menu size={18}/></button></div>{nav.map(n=><button className={view===n.key?'side-link active':'side-link'} key={n.key} onClick={()=>{if(['sales','procurement','inventory','equipment'].includes(n.key))setPopup(n.key);else setView(n.key);setMobile(false)}}><n.icon size={17}/><span>{n.label}</span>{['dashboard','sales','manufacture','equipment'].includes(n.key)&&<ChevronDown size={12}/>}</button>)}<div className="shortcuts"><small>Shortcuts</small><button className="side-link"><Bell size={16}/>Stock Level Alerts</button><button className="side-link"><Package size={16}/>Create Inbound</button><button className="side-link"><Package size={16}/>Create Outbound</button></div></aside><main className="main">{view==='dashboard'?<Dashboard setPopup={setPopup}/>:view==='equipment'?<Equipment/>:<><Hero title={title} sub={view==='locations'?'Locations list':'Operational list'}/><section className="panel"><h2>{title}</h2><p className="muted">Select an operational record to review its details.</p></section></>}<footer>Copyright © 2025 Artiselite Sdn Bhd</footer></main>{popup==='sales'&&<Modal title="Sales Order" onClose={()=>setPopup('')}><DataTable kind="sales"/></Modal>}{popup==='procurement'&&<Modal title="Procurement" onClose={()=>setPopup('')}><DataTable kind="sales"/></Modal>}{popup==='inventory'&&<Modal title="Inventory / Assets" onClose={()=>setPopup('')}><DataTable kind="inventory"/></Modal>}{popup==='equipment'&&<Modal title="Equipment & Crew" onClose={()=>setPopup('')}><Equipment/></Modal>}</div>}
